[project]
name = "amqcsldb-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "stickie", email = "71910589+FieryIceStickie@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
